config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: :"users/omniauth_callbacks"
  }

  get 'users/mine' => 'users#show'
  resources :articles
  root 'top#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :manage, :all           # allow superadmins to do anything
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  
  validates :title, presence: true
  validates :picture, presence: true

  mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles

  mount_uploader :avatar, AvatarUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :confirmable
  
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    unless user
      user = User.new(
          name:     auth.extra.raw_info.name,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          image_url:   auth.info.image,
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end
  
  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20],
      )
      user.skip_confirmation!
      user.save
    end
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  PERMISSIBLE_ATTRIBUTES = [:name, :avatar, :avatar_cache]
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, :alert => exception.message
  end

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:destroy, :update]

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      redirect_to :root, notice: '記事を作成しました'
    else
      render template: 'top/index'
    end
  end

  def update
    if @article.update(article_params)
      redirect_to :root, notice: '記事を更新しました'
    else
      respond_to do |format|
        format.json { render json: @article.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy

    redirect_to :root, alert: '記事を削除しました'
  end

  private
    def article_params
      params.require(:article).permit(:title, :content, :picture)
    end

    def set_article
      @article = Article.find(params[:id])
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :authenticate_user!

  def index
    @article = Article.new
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end

  protected

  def update_resource(resource, params)
    if current_user.provider.nil?
      resource.update_with_password(params)
    else
      params.delete('current_password')
      resource.update_without_password(params)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def profile_img(user, options = {})
    options.store :alt, user.name
    return image_tag(user.avatar, options) if user.avatar?

    unless user.provider.blank?
      img_url = user.image_url
    else
      img_url = 'silhouette-human-256.png'
    end
    image_tag(img_url, options)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><canvas id="brand-mark" width="200" height="20"></canvas></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left" id="search-content" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= users_mine_path %>"><img src="<%= image_path 'header/silhouette-human-32.png'%>" width="20" height="20"></a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instagramish</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if user_signed_in? %>
    <%= render 'application/header' %>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/top/index.html.erb
<% if notice %>
  <p class="alert alert-success text-center"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger text-center"><%= alert %></p>
<% end %>
<div class="col-md-offset-3 col-md-6">
  <div class="row" style="border: solid 1px #efefef; padding:15px; margin-bottom: 15px">
    <% if @article.errors.any? %>
      <div id="error_explanation">
        <h2><%= @article.errors.count %>件のエラーがあります。</h2>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_for @article do |f| %>
      <div class="form-group">
        <%= f.text_field :title, placeholder: "タイトル", class: "form-control"%>
      </div>
      <div class="form-group">
        <%= f.text_area :content, placeholder: "コメント", class: "form-control"%>
      </div>
      <div class="form-group">
        <%= f.file_field :picture %>
      </div>
      <%= f.submit "投稿", class: "btn btn-primary pull-right"%>
    <% end %>
  </div>

  <% Article.all.order('updated_at DESC').each do |article| %>
    <div class="row" style="border: solid 1px #efefef; padding:15px; margin-bottom: 15px">
      <p><%= profile_img article.user, style: "width: 30px; height: 30px; border-radius:75px; margin-right: 10px" %><%= article.user.name %></p>
      <p><%= article.title %></p>
      <p><%= image_tag article.picture, alt: article.title, style: 'width: 100%' %></p>
      <%= simple_format article.content %>
      <%= form_for article, url: article_path(article), method: :delete  do |f| %>
        <%= f.submit '削除', class: 'btn btn-danger pull-right', data: { confirm: '本当に削除しますか？' }%>
      <% end %>
      <button class="btn btn-primary pull-right" onclick="openEditModal('<%= article.title %>', `<%= article.content%>`, '<%= article_path(article) %>')">編集</button>
      <%#= form_for article, url: edit_article_path(article) do |f| %>
        <%#= f.submit '編集', class: 'btn btn-primary pull-right'%>
      <%# end %>
    </div>
  <% end %>

  <div class="modal fade" id="modal-edit-article" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">編集</h4>
        </div>
        <div class="modal-body">
          <div class="container-fluid">
            <div class="row">
              <div id="m_edit_error_explanation"></div>
              <%= form_tag article_path(:json), method: :patch, remote: true, authenticity_token: true do %>
                <div class="form-group">
                 <%= text_field_tag 'article[title]', nil, placeholder: 'タイトル', class: 'form-control', id: 'edit-title' %>
                </div>
                <div class="form-group">
                  <%= text_area_tag 'article[content]', nil, placeholder: 'コメント', class: 'form-control', id: 'edit-content' %>
                </div>
                <%=  file_field_tag 'article[picture]' %>
    
                <%= submit_tag '更新', class: "btn btn-primary pull-right" %>
              <% end %>
            </div>
          </div>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-offset-2 col-md-8 col-xs-offset-2 col-xs-8">
    <div class="col-md-4 col-xs-4">
      <%= profile_img current_user, style: "width: 150px; height: 150px; border-radius:75px; border: solid 1px #000000;" %>
    </div>
    <div class="col-md-8 col-xs-8">
      <p><%= @user.name %></p>
      <p><%= @user.email %></p>
      <ul style="display: flex; list-style: none">
        <li style="margin-right: 10px">
          <span>投稿</span>
          <span><%= @user.articles.count %></span>
          <span>件</span>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-offset-4 col-md-4 col-xs-offset-4 col-xs-4">
    <%= form_for current_user, url: destroy_user_session_path, method: :delete, html: { class: 'form-group' } do |f| %>
      <%= f.submit "ログアウト", class: "btn btn-danger btn-block" %>
    <% end %>
    <%= form_for current_user, url: edit_user_registration_path, method: :get do |f| %>
      <%= f.submit "編集", class: "btn btn-default btn-block" %>
    <% end %>
  </div>
</div>